results.docx : results.md nextSteps.md extra.css
	cat results.md nextSteps.md | pandoc -s -c extra.css -o results.docx -

implementation.docx : implementation.md nextSteps.md extra.css
	cat implementation.md nextSteps.md | pandoc -s -c extra.css -o implementation.docx -

